//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RunningLog.rc
//
#define ID_OPTIONS_GOTODATE             0
#define ID_OPTIONS_ADDLOCATIONRUN       1
#define ID_OPTIONS_ADDLOCATIONBIKE      2
#define IDC_ADDRUNLOC                   2
#define ID_OPTIONS_ADDLOCATIONSWIM      3
#define IDC_ADDBIKELOC                  3
#define ID_ADDDATA                      3
#define IDC_COPYLIST                    3
#define IDB_CHOOSEDATAFILE              3
#define ID_OPTIONS_ADDLOCATIONSTRENGTH  4
#define IDC_ADDSWIMLOC                  4
#define ID_VIEW_SHOESUMMARYBIKE         5
#define IDC_ADDSTRENGTHLOC              5
#define ID_VIEW_SHOESUMMARYRUN          6
#define IDC_ADDRUNCOURSE                6
#define IDR_MANIFEST                    7
#define ID_MISC_DISTCONVERT             7
#define IDC_ADDBIKECOURSE               7
#define IDOK2                           8
#define IDC_ADDSWIMCOURSE               8
#define ID_FILE_CONVERT3                8
#define ID_EDITNOTES                    9
#define IDC_ADDDUATHLONCOURSE           9
#define ID_OPTIONS_ADDSHOESBIKE         10
#define IDC_ADDTRIATHLONCOURSE          10
#define IDCANCEL2                       11
#define IDC_ADDRUNSHOES                 11
#define IDD_OPENUSERDLG                 12
#define IDC_ADDBIKESHOES                12
#define IDD_ABOUTBOX                    13
#define IDC_ADDBIKE                     13
#define IDR_MAINFRAME                   14
#define IDR_RunningLogTYPE              15
#define ID_CHILDCURMONTH                16
#define IDR_CONTEXTMENU                 17
#define ID_CHILDPREVMONTH               18
#define ID_CHILDNEXTMONTH               19
#define ID_FILE_OPENUSER                20
#define ID_FILE_CLOSEUSER               21
#define ID_FILE_ADDUSER                 22
#define ID_OPTIONS_USEROPTIONS          23
#define ID_OPTIONS_ADDSHOESRUN          24
#define ID_OPTIONS_ADDCOURSERUN         25
#define IDD_ADDUSERDLG                  26
#define ID_OPTIONS_ADDWORKOUT           27
#define ID_OPTIONS_GOTODAY              28
#define IDD_ADDCOURSERUNDLG             29
#define ID_GRAPHS_MILEAGEDAY            30
#define IDD_ADDSHOESRUNDLG              31
#define IDD_OPTIONSDLG                  32
#define IDD_OPTIONSCOLORSDLG            32
#define ID_GRAPHS_WEIGHTDAY             33
#define IDD_ADDWORKOUTSTARTDLG          34
#define ID_MISC_PACECALC                35
#define IDD_ADDUPCOMINGRACEDLG          36
#define ID_VIEW_PRSDUATHLON             37
#define ID_VIEW_DAYSUMMARY              38
#define ID_VIEW_DAYSUMMARYRUN           38
#define IDD_ADDLOCATIONRUNDLG           39
#define ID_MISC_WEEKSUMMARY             40
#define ID_VIEW_WEEKSUMMARY             41
#define ID_VIEW_WEEKSUMMARYRUN          41
#define IDD_ADDWORKOUTRACE              42
#define IDD_ADDRACERUN                  43
#define IDD_ADDWORKOUTLOCATION          44
#define ID_MISC_MONTHSUMMARY            45
#define ID_VIEW_MONTHSUMMARY            46
#define ID_VIEW_MONTHSUMMARYRUN         46
#define IDD_ADDRUNWORKOUTPOOL           47
#define ID_FILE_SAVEUSER                48
#define ID_MISC_PACECALCULATOR          49
#define ID_VIEW_PERSONALRECORDS         50
#define ID_HELP_HELPTOPICS              52
#define ID_VIEW_CURRENTNOTES            53
#define IDD_ADDSTRENGTHWORKOUTABS       54
#define ID_VIEW_FULLSUMMARY             55
#define ID_VIEW_FULLSUMMARYRUN          55
#define IDD_ADDRUNWORKOUTEZ             56
#define IDD_ADDWORKOUTNORMAL            57
#define ID_VIEW_GRAPH                   58
#define ID_VIEW_GRAPHLARGE              58
#define IDD_ADDRUNWORKOUTNORMAL         59
#define IDD_ADDWORKOUTTREADMILL         60
#define ID_VIEW_CUSTOMSUMMARY           61
#define ID_VIEW_CUSTOMSUMMARYRUN        61
#define IDD_ADDRUNWORKOUTTREADMILL      62
#define IDD_ADDWORKOUTMISC              63
#define ID_OPTIONS_ADDUPCOMINGRACE      64
#define IDD_ADDRUNWORKOUTOTHER          65
#define IDD_ADDWORKOUTHILLS             66
#define IDD_ADDRUNWORKOUTHILLS          67
#define IDD_ADDWORKOUTTEMPO             68
#define IDD_ADDRUNWORKOUTTEMPO          69
#define ID_OPTIONS_ADDCOURSEBIKE        70
#define IDD_ADDWORKOUTINTERVALS         71
#define IDD_ADDRUNWORKOUTINTERVALS      72
#define ID_OPTIONS_ADDCOURSESWIM        73
#define ID_VIEW_CURRENTNOTES161         74
#define ID_VIEW_FULLSUMMARY162          75
#define ID_VIEW_SHOESUMMARY163          76
#define ID_Menu164                      77
#define IDD_CURRENTNOTESDLG             78
#define IDD_DMFSUMMARY                  79
#define IDD_BIKESUMMARYDLG              79
#define IDD_DMFSUMMARYDLG               80
#define IDD_DMFRUNSUMMARYDLG            80
#define IDD_GOTODAYDLG                  81
#define IDB_DAVEHEAD                    82
#define IDD_PERSONALRECORDSDLG          83
#define IDD_PRDLG                       84
#define IDD_PRRUNDLG                    85
#define IDI_CURRENTDAY                  86
#define IDI_INJURY                      87
#define IDI_LONGDAY                     88
#define ID_Menu181                      90
#define IDD_DIALOG1                     92
#define IDD_SHEETSWIMEZPAGE             92
#define IDD_TRACKPRDLG                  93
#define ID_VIEW_CUSTOMSUMMARY187        94
#define IDD_GETDATESDLG                 95
#define IDD_SHOESUMMARYDLG              96
#define IDD_SHOESUMMARYRUNDLG           97
#define IDB_LEFTARROW                   98
#define IDB_LEFTARROWGRAY               99
#define IDB_RIGHTARROWGRAY              100
#define IDB_RIGHTARROW                  101
#define IDD_HELPDLG                     102
#define IDD_HELPPAGE                    102
#define IDD_PACECALCDLG                 103
#define IDC_DELETE                      103
#define IDC_SAVE                        104
#define IDD_SHEETWORKOUT                105
#define IDC_LOAD                        105
#define IDC_SIN                         106
#define ID_OPTIONS_ADDUPCOMINGRACE203   107
#define IDC_ARCSIN                      107
#define IDD_WORKOUTSTARTDLG             108
#define IDC_SINH                        108
#define IDI_UPCOMINGRACE                109
#define IDC_ARSINH                      109
#define IDR_CHARTMENU                   110
#define IDC_COS                         110
#define ID_FILE_SAVEAS                  111
#define IDC_ARCCOS                      111
#define IDD_ADDBIKECOURSEDLG            112
#define IDC_COSH                        112
#define IDD_ADDCOURSEBIKEDLG            113
#define IDC_ARCOSH                      113
#define IDD_ADDSWIMCOURSEDLG            114
#define IDC_TAN                         114
#define IDD_ADDCOURSESWIMDLG            115
#define IDC_ARCTAN                      115
#define IDD_ADDDUATHLONCOURSE           116
#define IDC_TANH                        116
#define IDD_ADDCOURSEDUATHLONDLG        117
#define IDC_ARTANH                      117
#define IDD_ADDTRIATHLONCOURSE          118
#define IDC_EXP                         118
#define IDD_ADDCOURSETRIATHLONDLG       119
#define IDC_LN                          119
#define IDD_ADDBIKELOCATIONDLG          120
#define IDC_INT                         120
#define IDD_ADDLOCATIONBIKEDLG          121
#define IDC_ABS                         121
#define IDD_ADDSWIMLOCATION             122
#define IDC_10X                         122
#define IDD_ADDLOCATIONSWIMDLG          123
#define IDC_LOG                         123
#define IDD_ADDSTRENGTHLOCATION         124
#define IDC_RAD                         124
#define IDD_ADDLOCATIONSTRENGTHDLG      125
#define IDC_DEG                         125
#define IDD_ADDBIKESHOESDLG             126
#define IDC_X2                          126
#define IDD_ADDSHOESBIKEDLG             127
#define IDC_SQR                         127
#define IDD_SWIMPRDLG                   128
#define IDC_PI                          128
#define IDD_ADDRUNWORKOUTHARD           129
#define IDD_ADDBIKEWORKOUTNORMAL        130
#define IDD_ADDBIKEWORKOUTEZ            131
#define IDC_KLAMMER_AUF                 131
#define IDD_ADDBIKEWORKOUTHARD          132
#define IDC_KLAMMER_ZU                  132
#define IDD_ADDBIKEWORKOUTTRAINER       133
#define IDC_GETEILT                     133
#define IDD_ADDBIKEWORKOUTINTERVALS     134
#define IDC_MAL                         134
#define IDD_ADDBIKEWORKOUTHILLS         135
#define IDC_UNDO                        135
#define IDD_ADDBIKEWORKOUTOTHER         136
#define IDC_B                           136
#define IDD_ADDSWIMWORKOUTEASY          137
#define IDD_ADDSWIMWORKOUTEZ            137
#define IDC_F                           137
#define IDD_ADDSWIMWORKOUTNORMAL        138
#define IDC_MINUS                       138
#define IDD_ADDSWIMWORKOUTHARD          139
#define IDC_Q                           139
#define IDD_ADDSWIMWORKOUTDRILLS        140
#define IDC_X                           140
#define IDD_ADDSWIMWORKOUTOPENWATER     141
#define IDC_J                           141
#define IDD_ADDSWIMWORKOUTINTERVALS     142
#define IDC_PLUS                        142
#define IDD_ADDSWIMWORKOUTOTHER         143
#define IDC_K                           143
#define IDD_ADDSTRENGTHWORKOUTWEIGHTS   144
#define IDC_M                           144
#define IDD_ADDSTRENGTHWORKOUTOTHER     145
#define IDC_N                           145
#define IDD_ADDRACEBIKE                 146
#define IDC_P                           146
#define IDD_ADDRACESWIM                 147
#define IDC_PKT                         147
#define IDD_ADDRACEDUATHLON             148
#define IDC_HOCH                        148
#define IDD_ADDRACETRIATHLON            149
#define IDC_C                           149
#define ID_Menu240                      150
#define IDC_EDIT_B                      150
#define ID_VIEW_PRSBIKE                 151
#define IDC_EDIT_F                      151
#define ID_VIEW_PRSRUN                  152
#define IDC_EDIT_Q                      152
#define ID_VIEW_PRSSWIM                 153
#define IDC_EDIT_X                      153
#define ID_OPTIONS_ADDCOURSEDUATHLON    154
#define IDC_EDIT_J                      154
#define ID_VIEW_PRSTRIATHLON            155
#define IDC_EDIT_K                      155
#define ID_OPTIONS_ADDCOURSETRIATHLON   156
#define IDC_EDIT_M                      156
#define ID_ADDSHOES_BIKE                157
#define IDC_EDIT_N                      157
#define ID_OPTIONS_ADDBIKE              158
#define IDC_EDIT_P                      158
#define ID_OPTIONS_RETIREBIKE           159
#define IDC_Y                           159
#define ID_OPTIONS_RETIRESHOES          160
#define IDC_EDIT_Y                      160
#define IDD_SHOESUMMARYBIKEDLG          161
#define IDC_BLOWER                      161
#define IDD_PRBIKEDLG                   162
#define IDC_EDIT_BLOWER                 162
#define IDD_PRSWIMDLG                   163
#define IDC_FLOWER                      163
#define IDD_PRDUATHLONDLG               164
#define IDC_EDIT_FLOWER                 164
#define IDD_PRTRIATHLONDLG              165
#define IDC_JLOWER                      165
#define IDC_EDIT_JLOWER                 166
#define IDC_KLOWER                      167
#define IDC_EDIT_KLOWER                 168
#define IDD_ADDBIKEDLG                  169
#define IDC_MLOWER                      169
#define IDC_EDIT_MLOWER                 170
#define ID_OPTIONS_RETIRESHOESRUN       171
#define IDC_NLOWER                      171
#define ID_OPTIONS_RETIRESHOESBIKE      172
#define IDC_EDIT_NLOWER                 172
#define IDC_PLOWER                      173
#define ID_VIEW_BIKESUMMARY             174
#define IDC_EDIT_LOWERP                 174
#define ID_VIEW_DAYSUMMARYBIKE          175
#define IDC_QLOWER                      175
#define ID_VIEW_WEEKSUMMARYBIKE         176
#define IDC_EDIT_QLOWER                 176
#define ID_VIEW_MONTHSUMMARYBIKE        177
#define IDC_XLOWER                      177
#define ID_VIEW_FULLSUMMARYBIKE         178
#define IDC_EDIT_XLOWER                 178
#define ID_VIEW_CUSTOMSUMMARYBIKE       179
#define IDC_YLOWER                      179
#define ID_VIEW_DAYSUMMARYSWIM          180
#define IDC_EDIT_YLOWER                 180
#define ID_VIEW_WEEKSUMMARYSWIM         181
#define IDC_EDIT_C                      181
#define ID_VIEW_MONTHSUMMARYSWIM        182
#define IDC_EDIT_ZLOWER                 182
#define ID_VIEW_FULLSUMMARYSWIM         183
#define ID_VIEW_CUSTOMSUMMARYSWIM       184
#define ID_VIEW_DAYSUMMARYSTRENGTH      185
#define ID_VIEW_WEEKSUMMARYSTRENGTH     186
#define ID_VIEW_MONTHSUMMARYSTRENGTH    187
#define ID_VIEW_FULLSUMMARYSTRENGTH     188
#define ID_VIEW_CUSTOMSUMMARYSTRENGTH   189
#define ID_VIEW_WEEKSUMMARYMULTI        190
#define ID_VIEW_RUNNINGSUMMARIES        190
#define ID_VIEW_MONTHSUMMARYMULTI       191
#define IDD_DMFBIKESUMMARYDLG           191
#define ID_VIEW_FULLSUMMARYMULTI        192
#define IDD_DMFSWIMSUMMARYDLG           192
#define ID_VIEW_CUSTOMSUMMARYMULTI      193
#define IDD_DMFSTRENGTHSUMMARYDLG       193
#define IDD_DMFMULTISUMMARYDLG          194
#define IDI_CONVERTER                   195
#define IDD_DISTCONVERTERDLG            196
#define ID_MISC_DISTCONVERTER           197
#define IDD_SHEETRUNEZPAGE              204
#define IDD_SHEETRUNHARDPAGE            205
#define IDD_SHEETRUNHILLSPAGE           206
#define IDD_SHEETRUNINTERVALSPAGE       207
#define IDD_SHEETRUNMISCPAGE            208
#define IDD_SHEETRUNNORMALPAGE          209
#define IDD_SHEETRUNPOOLPAGE            210
#define IDD_SHEETRUNTEMPOPAGE           211
#define IDD_SHEETRUNTREADMILLPAGE       212
#define IDD_SHEETBIKEEZPAGE             213
#define IDD_SHEETBIKEHARDPAGE           214
#define IDD_SHEETBIKEHILLSPAGE          215
#define IDD_SHEETBIKEINTERVALSPAGE      216
#define IDD_SHEETBIKEMISCPAGE           217
#define IDD_SHEETBIKENORMALPAGE         218
#define IDD_SHEETBIKETRAINERPAGE        219
#define IDD_SHEETSWIMDRILLSPAGE         220
#define IDD_SHEETSWIMHARDPAGE           222
#define IDD_SHEETSWIMINTERVALSPAGE      223
#define IDD_SHEETSWIMMISCPAGE           224
#define IDD_SHEETSWIMNORMALPAGE         225
#define IDD_SHEETSWIMOPENWATERPAGE      226
#define IDD_SHEETSTRENGTHABSPAGE        227
#define IDD_SHEETSTRENGTHMISCPAGE       228
#define IDD_SHEETSTRENGTHWEIGHTSPAGE    229
#define IDD_SHEETRACERUNPAGE            230
#define IDD_SHEETRACEBIKEPAGE           231
#define IDD_SHEETRACESWIMPAGE           232
#define IDD_SHEETRACEDUATHLONPAGE       233
#define IDD_SHEETRACETRIATHLONPAGE      234
#define IDB_SPLASH3                     236
#define IDD_GRAPHREMINDDLG              238
#define ID_HELP_CAPABILITIES            239
#define IDD_SWIMPRSUMMARYDLG            240
#define IDD_TRACKPRSUMMARYDLG           241
#define ID_PERSONALRECORDS_ALLPOOL      242
#define ID_PERSONALRECORDS_ALLTRACK     243
#define IDD_VERSIONCONVERTERDLG         244
#define ID_FILE_CONVERTRUNNINGLOG1      245
#define IDD_CONVERTLOCATIONDLG          246
#define IDD_CONVERTRUNBIKEDLG           247
#define IDD_CONVERTRUNPOOLDLG           248
#define IDD_CONVERTRUNWEIGHTSDLG        249
#define IDD_CONVERTSUCCESS              250
#define IDC_GRABHAND                    257
#define IDC_GRABHAND2                   258
#define IDD_FORMULADLG                  263
#define IDI_DAYSUMMARY                  264
#define IDI_RUNNER                      265
#define IDD_LOCATIONSUMMARYRUNDLG       266
#define IDD_LOCATIONSUMMARYBIKEDLG      267
#define IDD_LOCATIONSUMMARYSWIMDLG      268
#define IDD_LOCATIONSUMMARYSTRENGTHDLG  269
#define IDD_RACESUMMARYRUNDLG           270
#define IDD_RACESUMMARYBIKEDLG          271
#define IDD_RACESUMMARYSWIMDLG          272
#define IDD_RACESUMMARYDUATHLONDLG      273
#define IDD_RACESUMMARYTRIATHLONDLG     274
#define ID_VIEW_LOCATIONSUMMARY         275
#define ID_VIEW_RACESUMMARY             276
#define IDI_INJURY2                     277
#define IDD_DELETEWORKOUTDLG            278
#define ID_OPTIONS_DELETEWORKOUT279     279
#define IDD_OPTIONSCALENDARDLG          280
#define IDD_OPTIONSUNITDLG              281
#define IDD_OPTIONSDATABIKEDLG          282
#define IDD_OPTIONSDATASWIMDLG          283
#define IDD_OPTIONSDATASTRDLG           284
#define IDD_OPTIONSDATARUNDLG           285
#define IDD_OPTIONSDATARACERUNDLG       286
#define IDD_OPTIONSDATARACEBIKEDLG      287
#define IDD_OPTIONSDATARACESWIMDLG      288
#define IDD_OPTIONSDATARACETRIDLG       289
#define IDD_OPTIONSDATARACEDUDLG        290
#define IDI_BRICK                       291
#define IDD_OPTIONSDATASTARTDLG         292
#define IDI_JAMBAJUICE                  293
#define IDD_ADDALLTYPESDLG              294
#define ID_OPTIONS_ADDMULTIPLEITEMS     295
#define IDI_TTIPINFO                    296
#define IDD_EDITUSERDLG                 297
#define IDI_SICK                        298
#define IDD_CALORIEDLG                  299
#define IDD_HELPICONSPAGE               300
#define IDD_PECHARTLARGEDLG             301
#define IDD_PECHARTGENERALDLG           302
#define IDD_PECHARTMEDIUMDLG            303
#define IDD_PECHARTSMALLDLG             304
#define IDD_PECHARTSERIESDLG            305
#define IDD_PECHARTSERIES2DLG           306
#define IDD_SEARCHDLG                   307
#define IDD_SEARCHHELPDLG               308
#define IDB_PACEFORMULA                 308
#define IDD_PRINTTOFILEDLG              309
#define IDR_GIF1                        309
#define IDD_ADDBIKEWORKOUTMOUNTAINBIKE  310
#define IDD_SHEETBIKEMOUNTAINBIKEPAGE   311
#define IDB_BITMAP1                     311
#define IDD_ADDUPCOMINGWORKOUTDLG       312
#define IDD_ADDBIKEWORKOUTTIMETRIAL     313
#define IDD_SHEETBIKETIMETRIALPAGE      314
#define IDB_BITMAP2                     315
#define IDD_INJURYTRACKERDLG            317
#define IDD_ADDINJURYDLG                318
#define IDD_GETTINGSTARTEDDLG           319
#define IDC_0                           500
#define IDC_1                           501
#define IDC_2                           502
#define IDC_3                           503
#define IDC_4                           504
#define IDC_5                           505
#define IDC_6                           506
#define IDC_7                           507
#define IDC_8                           508
#define IDC_9                           509
#define IDC_UNITS1                      1000
#define IDC_FIRSTNAME                   1001
#define IDC_UNITS2                      1001
#define IDC_FORMELEINGABE               1001
#define IDC_LASTNAME                    1002
#define IDC_DIST2                       1002
#define IDC_HEIGHT                      1003
#define IDC_HEARTRATE                   1004
#define IDC_SEXMALE                     1005
#define IDC_L1HEARTRATE                 1005
#define IDC_SEXFEMALE                   1006
#define IDC_L3HEARTRATE                 1006
#define IDC_BASEMINUTES                 1007
#define IDC_BASEMINUTESRUN              1007
#define IDC_UNITSAMERICAN               1007
#define IDC_BASEMILES                   1008
#define IDC_BASEMILESRUN                1008
#define IDC_UNITSMETRIC                 1008
#define IDC_STARTDAY                    1009
#define IDC_BASEMINUTESBIKE             1009
#define IDC_USERNAME                    1010
#define IDC_BASEMILESBIKE               1010
#define IDC_STARTMONTH                  1011
#define IDC_BASEMINUTESSWIM             1011
#define IDC_BRANDNAME                   1012
#define IDC_BASEMILESSWIM               1012
#define IDC_MODELNAME                   1013
#define IDC_ENDDAY                      1014
#define IDC_LENGTH                      1015
#define IDC_ADDTOGRAPHNUM               1015
#define IDC_SHOESIZE                    1016
#define IDC_LENGTHWHOLE                 1017
#define IDC_SHOESIZEWHOLE               1018
#define IDC_STARTYEAR                   1019
#define IDC_SHOESIZEFRAC                1020
#define IDC_COMBINATION                 1020
#define IDC_ENDYEAR                     1021
#define IDC_NOTES                       1022
#define IDC_COURSENAME                  1023
#define IDC_CITYSTATE                   1024
#define IDC_RESETDEFAULT                1025
#define IDC_STATE                       1026
#define IDC_RESETDEFAULT2               1026
#define IDC_RANDOMCOLORS                1026
#define IDC_COLORNORMALDAY              1027
#define IDC_COLORCALBG                  1028
#define IDC_COLOROUTOFMONTH             1029
#define IDC_WORKOUTTYPE                 1030
#define IDC_COLORRACEDAY                1030
#define IDC_RUNTIME                     1031
#define IDC_COLORUPCOMINGRACEDAY        1031
#define IDC_ACTIVITYTYPE                1032
#define IDC_COLORUPCOMINGWORKOUTDAY     1032
#define IDC_RUNDIST                     1033
#define IDC_TIMEMINUTES                 1034
#define IDC_TIMERACEMINUTES             1035
#define IDC_MINPERMILE                  1036
#define IDC_L1TIMERACEMINUTES           1036
#define IDC_TIMEOVERALLMINS             1037
#define IDC_OVERALLTIMERACEMINUTES      1037
#define IDC_INJURED                     1038
#define IDC_L1TIMEOVERALLMINS           1038
#define IDC_COLORWEEKSUMMARY            1039
#define IDC_TRANSITIONMINUTES23         1039
#define IDC_INJURED2                    1039
#define IDC_SHOESUSED                   1040
#define IDC_L3TIMEOVERALLMINS           1040
#define IDC_TIMESECONDS                 1041
#define IDC_L3TIMERACEMINUTES           1041
#define IDC_TIMERACESECONDS             1042
#define IDC_SPECIALMINUTES              1043
#define IDC_L1TIMERACESECONDS           1043
#define IDC_COLORMONTHSUMMARY           1044
#define IDC_OVERALLTIMERACESECONDS      1044
#define IDC_TIMERACEFRAC                1045
#define IDC_TRANSITIONSECONDS23         1045
#define IDC_COLORHILITEDAY              1046
#define IDC_L1TIMERACEFRAC              1046
#define IDC_DISTANCEFRAC                1047
#define IDC_OVERALLTIMERACEFRAC         1047
#define IDC_COLORBUTTON                 1048
#define IDC_L1DISTANCEFRAC              1048
#define IDC_SPECIALFRAC                 1048
#define IDC_TEMPERATURE                 1049
#define IDC_L3DISTANCEFRAC              1049
#define IDC_COLOREDITBG                 1049
#define IDC_COLORDAYOFWEEKTEXT          1050
#define IDC_L1TEMPERATURE               1050
#define IDC_STARTTIME                   1051
#define IDC_L3TEMPERATURE               1051
#define IDC_STARTTIMEHOUR               1052
#define IDC_L3TIMERACESECONDS           1052
#define IDC_STARTTIME3                  1052
#define IDC_PLACE                       1053
#define IDC_SPECIALDISTFRAC             1054
#define IDC_L3TIMERACEFRAC              1054
#define IDC_MONTH                       1055
#define IDC_STARTTIMEHOUR2              1055
#define IDC_ENDMONTH                    1056
#define IDC_SEARCH1                     1056
#define IDC_COLORDAYOFMONTHTEXT         1057
#define IDC_RELATION1                   1057
#define IDC_STARTTIMEMINUTE             1058
#define IDC_SEARCH7                     1058
#define IDC_RACENUMBER                  1059
#define IDC_RELATION7                   1059
#define IDC_COLORANNOTATIONTEXT         1060
#define IDC_SEARCH2                     1060
#define IDC_PREVNIGHTHOUR               1061
#define IDC_RELATION2                   1061
#define IDC_TIMEOVERALLSECONDS          1062
#define IDC_SEARCH3                     1062
#define IDC_COLORGRADSTART              1063
#define IDC_L1TIMEOVERALLSECONDS        1063
#define IDC_RELATION3                   1063
#define IDC_PREVNIGHTMINUTE             1064
#define IDC_L3TIMEOVERALLSECONDS        1064
#define IDC_SEARCH4                     1064
#define IDC_SPECIALSECONDS              1065
#define IDC_PREVNIGHTMINUTE3            1065
#define IDC_RELATION4                   1065
#define IDC_PRMINUTES                   1066
#define IDC_SEARCH5                     1066
#define IDC_AVERAGEHR                   1067
#define IDC_RELATION5                   1067
#define IDC_COLORGRADEND                1068
#define IDC_SEARCH6                     1068
#define IDC_WEIGHTWHOLE                 1069
#define IDC_RELATION6                   1069
#define IDC_PRSECONDS                   1070
#define IDC_INDCALORIES                 1070
#define IDC_SEARCH8                     1070
#define IDC_WINDTYPE                    1071
#define IDC_RELATION8                   1071
#define IDC_PREVNIGHTMINUTE2            1072
#define IDC_SEARCH9                     1072
#define IDC_WEIGHTFRAC                  1073
#define IDC_RELATION9                   1073
#define IDC_PRFRAC                      1074
#define IDC_SEARCH10                    1074
#define IDC_CHOPPINESS                  1075
#define IDC_RELATION10                  1075
#define IDC_TIMEAM                      1076
#define IDC_TRAINERNUM                  1076
#define IDC_SEARCH11                    1076
#define IDC_TIMEPM                      1077
#define IDC_RELATION11                  1077
#define IDC_PREVNIGHTSLEEP              1078
#define IDC_SEARCH12                    1078
#define IDC_COURSE                      1079
#define IDC_RELATION12                  1079
#define IDC_ADDCOURSE                   1080
#define IDC_ENDMONTH2                   1080
#define IDC_TIMEHOURS                   1081
#define IDC_SEPARATEWITH                1081
#define IDC_TIMERACEHOURS               1082
#define IDC_LOCATION                    1083
#define IDC_L1TIMERACEHOURS             1083
#define IDC_PRHOURS                     1084
#define IDC_OVERALLTIMERACEHOURS        1084
#define IDC_ADDLOCATION                 1085
#define IDC_L3TIMERACEHOURS             1085
#define ID_DELETEUSER                   1086
#define IDC_WIND                        1087
#define IDC_DISTANCE                    1088
#define IDC_L1WIND                      1088
#define IDC_PACE                        1089
#define IDC_L3WIND                      1089
#define IDC_PACE2                       1090
#define IDC_L1DISTANCE                  1090
#define IDC_STARTTIMEWKT                1091
#define IDC_L2DISTANCE                  1091
#define IDC_SHOES                       1092
#define IDC_L3DISTANCE                  1092
#define IDC_INTERVALSHOES               1093
#define IDC_L1SHOES                     1093
#define IDC_SPECIALSHOES                1094
#define IDC_L3SHOES                     1094
#define IDC_RACEDISTANCE                1095
#define IDC_LONG                        1096
#define IDC_HILLDISTANCE                1097
#define IDC_LONG2                       1097
#define IDC_WEIGHT                      1098
#define IDC_L1RACEDISTANCE              1098
#define IDC_HILLMINUTES                 1099
#define IDC_L3RACEDISTANCE              1099
#define IDC_DATAFILE                    1099
#define IDC_DATE                        1100
#define IDC_WEIGHT2                     1100
#define IDC_AMPMSPIN                    1101
#define IDC_DATEEND                     1101
#define IDC_DATAFILE2                   1101
#define IDC_AMPM                        1102
#define IDC_DISTANCEWHOLE               1103
#define IDC_RACESHOES                   1104
#define IDC_SPECIALDISTWHOLE            1105
#define IDC_L1DISTANCEWHOLE             1105
#define IDC_LENGTHFRAC                  1106
#define IDC_L1RACESHOES                 1106
#define IDC_CITY                        1107
#define IDC_L3DISTANCEWHOLE             1107
#define IDC_LOCATIONNAME                1108
#define IDC_L3RACESHOES                 1108
#define IDC_RACEPACE                    1109
#define IDC_SPECIALPACE                 1110
#define IDC_L1RACEPACE                  1110
#define IDC_BIKENUM                     1111
#define IDC_L3RACEPACE                  1111
#define IDC_EASYNUM                     1112
#define IDC_HILLSNUM                    1113
#define IDC_INTERVALSNUM                1114
#define IDC_MISCNUM                     1115
#define IDC_NORMALNUM                   1116
#define IDC_POOLNUM                     1117
#define IDC_MOUNTAINNUM                 1117
#define IDC_RACENUM                     1118
#define IDC_TEMPONUM                    1119
#define IDC_TIMETRIALNUM                1119
#define IDC_TREADMILLNUM                1120
#define IDC_WEIGHTSNUM                  1121
#define IDC_TOTALNUM                    1122
#define IDC_BIKEMINS                    1123
#define IDC_SWIMINTERVALS               1123
#define IDC_EASYMINS                    1124
#define IDC_HILLSMINS                   1125
#define IDC_INTERVALSMINS               1126
#define IDC_MISCMINS                    1127
#define IDC_NORMALMINS                  1128
#define IDC_POOLMINS                    1129
#define IDC_MOUNTAINMINS                1129
#define IDC_RACEMINS                    1130
#define IDC_TEMPOMINS                   1131
#define IDC_TIMETRIALMINS               1131
#define IDC_TREADMILLMINS               1132
#define IDC_WEIGHTSMINS                 1133
#define IDC_HARDMINS                    1133
#define IDC_TOTALMINS                   1134
#define IDC_BIKEMILES                   1135
#define IDC_EASYMILES                   1136
#define IDC_HILLSMILES                  1137
#define IDC_INTERVALSMILES              1138
#define IDC_MISCMILES                   1139
#define IDC_NORMALMILES                 1140
#define IDC_POOLMILES                   1141
#define IDC_MOUNTAINMILES               1141
#define IDC_RACEMILES                   1142
#define IDC_TEMPOMILES                  1143
#define IDC_TIMETRIALMILES              1143
#define IDC_TREADMILLMILES              1144
#define IDC_WEIGHTSMILES                1145
#define IDC_HARDMILES                   1145
#define IDC_TOTALMILES                  1146
#define IDC_AVGWEIGHT                   1147
#define IDC_AVGHR                       1148
#define IDC_AVGSLEEP                    1149
#define IDC_AVGTEMP                     1150
#define IDC_DAY                         1151
#define IDC_TOTALPOINTS                 1151
#define IDC_AVGPACE                     1152
#define IDC_YEAR                        1153
#define IDC_COMPLETEREST                1154
#define IDC_WITHOUTRUNNING              1155
#define IDC_PRPACE                      1156
#define IDC_XAXIS                       1157
#define IDC_PACE1                       1158
#define IDC_YAXIS                       1159
#define IDC_INCREMENT                   1160
#define IDC_SMOOTH                      1161
#define IDC_ROTATIONINCREMENT           1161
#define IDC_DATAMARKERS                 1162
#define IDC_CHART                       1163
#define IDC_400MINS                     1164
#define IDC_MARKERTYPE                  1164
#define IDC_400SECS                     1165
#define IDC_LEGEND                      1165
#define IDC_400MS                       1166
#define IDC_MARKERSIZE                  1166
#define IDC_800MINS                     1167
#define IDC_ERRORBARS                   1167
#define IDC_DATERUN                     1168
#define IDC_DATALABELS                  1168
#define IDC_400PACE                     1168
#define IDC_800SECS                     1169
#define IDC_L1DATERUN                   1169
#define IDC_LEGENDPOS                   1169
#define IDC_POINTSELECTION              1169
#define IDC_PURCHASED                   1170
#define IDC_L2DATERUN                   1170
#define IDC_GRAPHTYPE                   1170
#define IDC_800PACE                     1170
#define IDC_400DATE2                    1170
#define IDC_800MS                       1171
#define IDC_L3DATERUN                   1171
#define IDC_TRENDLINE                   1171
#define IDC_LEGENDLOCATION              1171
#define IDC_WORKOUTS                    1172
#define IDC_TRANS1DATE                  1172
#define IDC_400DATE                     1172
#define IDC_800PACE2                    1172
#define IDC_1500MINS                    1173
#define IDC_TRANS2DATE                  1173
#define IDC_MINUTES                     1174
#define IDC_1500PACE                    1174
#define IDC_HELPNOTES                   1175
#define IDC_800DATE                     1175
#define IDC_1500SECS                    1176
#define IDC_MILES                       1177
#define IDC_1500DATE                    1177
#define IDC_WHOLEDIST1                  1178
#define IDC_1500MS                      1179
#define IDC_FIRSTUSED                   1180
#define IDC_1500PACE2                   1180
#define IDC_FRACDIST1                   1181
#define IDC_1600MINS                    1182
#define IDC_LASTUSED                    1183
#define IDC_DISTMKM1                    1184
#define IDC_1600SECS                    1185
#define IDC_DISTSPIN1                   1186
#define IDC_1600MS                      1187
#define IDC_HOURS1                      1188
#define IDC_1600PACE                    1188
#define IDC_TIME1                       1188
#define IDC_1MILEMINS                   1189
#define IDC_MINUTES1                    1190
#define IDC_1600DATE                    1190
#define IDC_1MILESECS                   1191
#define IDC_SECONDS1                    1192
#define IDC_1MILEMS                     1193
#define IDC_FRAC1                       1194
#define IDC_1MILEPACE                   1194
#define IDC_3200MINS                    1195
#define IDC_WHOLEDIST2                  1196
#define IDC_1MILEDATE                   1196
#define IDC_TIMEOVERALL                 1197
#define IDC_3200SECS                    1198
#define IDC_FRACDIST2                   1199
#define IDC_PREVSLEEP                   1200
#define IDC_3200MS                      1201
#define IDC_HOURS2                      1202
#define IDC_3200PACE                    1202
#define IDC_TIME2                       1202
#define IDC_SPECIALTIME                 1203
#define IDC_3200DATE                    1203
#define IDC_2MILEMINS                   1204
#define IDC_MINUTES2                    1205
#define IDC_SPECIALDIST                 1206
#define IDC_2MILESECS                   1207
#define IDC_SECONDS2                    1208
#define IDC_2MILEMS                     1209
#define IDC_FRAC2                       1210
#define IDC_2MILEPACE                   1210
#define IDC_5000MINS                    1211
#define IDC_DISTSPIN2                   1212
#define IDC_2MILEDATE                   1212
#define IDC_5000SECS                    1213
#define IDC_DISTMKM2                    1214
#define IDC_5000MS                      1215
#define IDC_10000MINS                   1216
#define IDC_SEIGEL                      1217
#define IDC_5000PACE                    1217
#define IDC_10000SECS                   1218
#define IDC_CONSTANT                    1219
#define IDC_5000DATE                    1219
#define IDC_LINE1                       1220
#define IDC_10000MS                     1221
#define IDC_LINE2                       1222
#define IDC_10000PACE                   1222
#define IDC_STEEPLEMINS                 1223
#define IDC_LINE3                       1223
#define IDC_STEEPLESECS                 1224
#define IDC_STEEPLEMS                   1225
#define IDC_3000MINS                    1226
#define IDC_3000SECS                    1227
#define IDC_L1LENGTHWHOLE               1228
#define IDC_STEEPLEPACE                 1228
#define IDC_3000MS                      1229
#define IDC_L1LENGTHFRAC                1230
#define IDC_3000PACE                    1230
#define IDC_L1PRHOURS                   1231
#define IDC_3000DATE                    1231
#define IDC_L1PRMINUTES                 1232
#define IDC_10000DATE                   1232
#define IDC_L1PRSECONDS                 1233
#define IDC_STEEPLEDATE                 1233
#define IDC_L1PRFRAC                    1234
#define IDC_L1PRPACE                    1235
#define IDC_L1NOTES                     1236
#define IDC_L2LENGTHWHOLE               1237
#define IDC_50MINS                      1238
#define IDC_OVERALLL1PRFRAC             1239
#define IDC_50PACE                      1239
#define IDC_L2LENGTHFRAC                1240
#define IDC_50DATE                      1240
#define IDC_50SECS                      1241
#define IDC_L2PRHOURS                   1242
#define IDC_50MS                        1243
#define IDC_L2PRMINUTES                 1244
#define IDC_100MINS                     1245
#define IDC_L2PRSECONDS                 1246
#define IDC_100PACE                     1246
#define IDC_100SECS                     1247
#define IDC_L2PRFRAC                    1248
#define IDC_100DATE                     1248
#define IDC_100MS                       1249
#define IDC_L2NOTES                     1250
#define IDC_200MINS                     1251
#define IDC_OVERALLNOTES                1252
#define IDC_200PACE                     1252
#define IDC_L2PRPACE                    1253
#define IDC_200DATE                     1253
#define IDC_200SECS                     1254
#define IDC_200MS                       1255
#define IDC_BIKE                        1256
#define IDC_COUNTONBIKE                 1257
#define IDC_COUNTONSHOES                1258
#define IDC_RACEBIKE                    1259
#define IDC_COUNTONSHOES2               1259
#define IDC_DISPLAYNAME                 1260
#define IDC_L3LENGTHWHOLE               1261
#define IDC_L3LENGTHFRAC                1262
#define IDC_L3PRHOURS                   1263
#define IDC_L3PRMINUTES                 1264
#define IDC_L3PRSECONDS                 1265
#define IDC_L3PRFRAC                    1266
#define IDC_L3NOTES                     1267
#define IDC_L3PRPACE                    1268
#define IDC_OVERALLPRHOURS              1269
#define IDC_OVERALLPRMINUTES            1270
#define IDC_OVERALLPRSECONDS            1271
#define IDC_OVERALLPRFRAC               1272
#define IDC_TRANSMITIONMINUTES12        1273
#define ID_ADDUSER                      1274
#define ID_RETIRESHOES                  1275
#define IDC_TRANSITIONSECONDS12         1276
#define IDC_L1PACE                      1277
#define IDC_TRANSMITIONMINUTES14        1278
#define IDC_L2TIMEOVERALLMINS           1279
#define IDC_TRANSITIONSECONDS2          1280
#define IDC_L2TIMEOVERALLSECONDS        1281
#define IDC_L2DISTANCEFRAC              1282
#define IDC_L2DISTANCEWHOLE             1283
#define IDC_L2PACE                      1284
#define IDC_L2TEMPERATURE               1285
#define IDC_L2WIND                      1286
#define IDC_L2HEARTRATE                 1287
#define IDC_L2SHOES                     1288
#define IDC_L2RACEDISTANCE              1289
#define IDC_L2TIMERACEHOURS             1290
#define IDC_L2TIMERACEMINUTES           1291
#define IDC_L2TIMERACESECONDS           1292
#define IDC_L2TIMERACEFRAC              1293
#define IDC_L2RACEBIKE                  1294
#define IDC_L2RACEPACE                  1295
#define IDC_L2RACESHOES                 1296
#define IDC_L3PACE                      1297
#define IDC_TRANSITIONSECONDS14         1298
#define IDC_L1CHOPPINESS                1299
#define IDC_TRANSITIONPRMINUTES2        1300
#define IDC_TRANSITIONSECONDS3          1301
#define IDC_TRANSMITIONMINUTES4         1302
#define IDC_TRANSITIONPRSECONDS2        1303
#define IDC_TRANSITIONSECONDS4          1304
#define IDC_TRANSITIONSECONDS1          1305
#define IDC_TRANSITIONMINUTES1          1306
#define IDC_TRANSITIONMINUTES2          1307
#define IDC_TRANSITIONPRMINUTES1        1308
#define IDC_TRANSITIONPRSECONDS1        1309
#define IDC_DISPLAYRUNNING              1312
#define IDC_DISPLAYBIKING               1313
#define IDC_DISPLAYSWIMMING             1314
#define IDC_DISPLAYSTRENGTH             1315
#define IDC_HARDNUM                     1315
#define IDC_DISPLAYRACES                1316
#define IDC_TRAINERMINS                 1316
#define IDC_TRAINERMILES                1317
#define IDC_DRILLSNUM                   1318
#define IDC_DRILLSMINS                  1319
#define IDC_DRILLSMILES                 1320
#define IDC_OPENWATERNUM                1321
#define IDC_OPENWATERMINS               1322
#define IDC_OPENWATERMILES              1323
#define IDC_ABSNUM                      1324
#define IDC_ABSMINS                     1325
#define IDC_RUNNINGNUM                  1327
#define IDC_RUNNINGMINS                 1328
#define IDC_RUNNINGMILES                1329
#define IDC_BIKINGNUM                   1330
#define IDC_BIKINGMINS                  1331
#define IDC_BIKINGMILES                 1332
#define IDC_SWIMMINGNUM                 1333
#define IDC_SWIMMINGMINS                1334
#define IDC_SWIMMINGMILES               1335
#define IDC_STRENGTHNUM                 1336
#define IDC_STRENGTHMINS                1337
#define IDC_STRENGTHMILES               1338
#define IDC_BIKINGPOINTS                1339
#define IDC_WITHOUTBIKING               1340
#define IDC_RUNNINGPOINTS               1341
#define IDC_WITHOUTSWIMMING             1342
#define IDC_STRENGTHPOINTS              1343
#define IDC_WITHOUTSTRENGTH             1344
#define IDC_SWIMMINGPOINTS              1345
#define IDC_WITHOUTBIKING2              1346
#define IDC_WITHOUTSWIMMING2            1347
#define IDC_WITHOUTSTRENGTH2            1348
#define IDC_RETIRESHOES                 1348
#define IDC_WITHOUTRUNNING2             1349
#define IDC_RETIREBIKE                  1349
#define IDC_COLOR                       1351
#define IDC_EMAIL                       1352
#define IDC_NPTEXTCOLOR                 1352
#define IDC_WEBSITE                     1353
#define IDC_NPBGCOLOR1                  1353
#define IDC_PTEXTCOLOR                  1354
#define IDC_XAXISTITLE                  1355
#define IDC_PBGCOLOR1                   1355
#define IDC_YAXISTITLE                  1356
#define IDC_NPBGCOLOR2                  1356
#define IDC_GRAPHTITLE                  1357
#define IDC_PBGCOLOR2                   1357
#define IDC_ADDNEWGRAPH                 1358
#define IDC_ADDEXISTINGGRAPH            1359
#define IDC_SERIESNAME                  1360
#define IDC_MAKEGRAPH                   1361
#define IDC_REMINDER                    1363
#define IDC_OPENFILE                    1365
#define IDC_OPENFILENAME                1366
#define IDC_PROGRESS                    1367
#define IDC_NEWFILENAME                 1368
#define IDC_CURRENTWORK                 1369
#define IDC_PROGRESSLEFT                1370
#define IDC_RUNOTHER                    1374
#define IDC_BIKEEZ                      1375
#define IDC_BIKEHARD                    1376
#define IDC_BIKEINTERVALS               1377
#define IDC_BIKEHILLS                   1378
#define IDC_BIKENORMAL                  1379
#define IDC_BIKEOTHER                   1380
#define IDC_BIKETRAINER                 1381
#define IDC_RUNPOOL                     1382
#define IDC_SWIMDRILLS                  1383
#define IDC_SWIMEZ                      1384
#define IDC_SWIMHARD                    1385
#define IDC_SWIMNORMAL                  1386
#define IDC_SWIMOTHER                   1387
#define IDC_SWIMOPENWATER               1388
#define IDC_STRENGTHABS                 1389
#define IDC_STRENGTHOTHER               1390
#define IDC_STRENGTHWEIGHTS             1391
#define IDC_BIKELOC                     1393
#define IDC_RUNNLOC                     1394
#define IDC_SWIMLOC                     1395
#define IDC_STRLOC                      1396
#define IDC_ROLLUP                      1397
#define IDC_ZLOWER                      1398
#define IDC_LOCATIONS                   1399
#define IDC_DATES                       1400
#define ID_DELETE                       1401
#define IDC_DISPLAY                     1402
#define IDC_RUNBASETIME                 1403
#define IDC_RUNBASEDIST                 1404
#define IDC_BIKEBASETIME                1405
#define IDC_BIKEBASEDIST                1406
#define IDC_SWIMBASEDIST                1407
#define IDC_SWIMBASETIME                1408
#define IDC_RUNDISTMILES                1409
#define IDC_RUNPACEMINDIST              1409
#define IDC_RUNDISTKM                   1410
#define IDC_RUNPACEDISTHR               1410
#define IDC_BIKEDISTMILES               1411
#define IDC_BIKEPACEMINDIST             1411
#define IDC_BIKEDISTKM                  1412
#define IDC_BIKEPACEDISTHR              1412
#define IDC_SWIMDISTMILES               1413
#define IDC_SWIMPACEMINDIST             1413
#define IDC_SWIMPACEMINDIST2            1413
#define IDC_SWIMDISTKM                  1414
#define IDC_SWIMPACEDISTHR              1414
#define IDC_SWIMPACEDISTHR2             1414
#define IDC_HEIGHTINCHES                1415
#define IDC_RUNBASEDIST5                1415
#define IDC_SWIMPACEMIN100M             1415
#define IDC_SWIMPACEMIN100M2            1415
#define IDC_HEIGHTCM                    1416
#define IDC_SWIMPACEMIN100Y2            1416
#define IDC_WEIGHTPOUNDS                1417
#define IDC_WEIGHTKG                    1418
#define IDC_LOCATIONMANDATORY           1418
#define IDC_MINUTESMANDATORY            1419
#define IDC_TEMPDEG                     1419
#define IDC_BIKEMANDATORY               1420
#define IDC_TEMPCELSIUS                 1420
#define IDC_SLEEPHOURS                  1420
#define IDC_SLEEP                       1420
#define IDC_TEMPMANDATORY               1421
#define IDC_HRMANDATORY                 1422
#define IDC_DISTWHOLEMANDATORY          1423
#define IDC_SECONDSMANDATORY            1424
#define IDC_SHOESMANDATORY              1425
#define IDC_COURSEMANDATORY             1425
#define IDC_SLEEPMINS                   1425
#define IDC_SPECSHOESMANDATORY          1426
#define IDC_RACENUMMANDATORY            1427
#define IDC_DISTDECMANDATORY            1428
#define IDC_SPECMINUTESMANDATORY        1429
#define IDC_SPECSECONDSMANDATORY        1430
#define IDC_SPECDISTWHOLEMANDATORY      1431
#define IDC_SPECHOURSMANDATORY          1431
#define IDC_SPECDISTDECMANDATORY        1432
#define IDC_SPECDECMANDATORY            1432
#define IDC_PLACEMANDATORY              1433
#define IDC_COURSEMANDATORY2            1434
#define IDC_TRANSMINUTESMANDATORY       1435
#define IDC_TRANSSECONDSMANDATORY       1436
#define IDC_L1SPECMINUTESMANDATORY      1437
#define IDC_L1SPECSECONDSMANDATORY      1438
#define IDC_L1SPECHOURSMANDATORY        1439
#define IDC_SPECDECMANDATORY2           1440
#define IDC_L1SPECDECMANDATORY          1440
#define IDC_L2BIKEMANDATORY             1441
#define IDC_L1MINUTESMANDATORY          1442
#define IDC_L1SECONDSMANDATORY          1443
#define IDC_L1DISTWHOLEMANDATORY        1444
#define IDC_L1DISTDECMANDATORY          1445
#define IDC_L1SHOESMANDATORY            1446
#define IDC_L1TEMPMANDATORY             1447
#define IDC_L1HRMANDATORY               1448
#define IDC_L1SPECSHOESMANDATORY        1449
#define IDC_L2MINUTESMANDATORY          1450
#define IDT_DIST                        1450
#define IDC_L2SECONDSMANDATORY          1451
#define IDT_TEMP                        1451
#define IDT_DISTL2                      1451
#define IDC_L2TEMPMANDATORY             1452
#define IDT_PACE                        1452
#define IDC_L2HRMANDATORY               1453
#define IDT_SPECIALDIST                 1453
#define IDC_L2DISTWHOLEMANDATORY        1454
#define IDT_SPECIALPACE                 1454
#define IDT_DISTL3                      1454
#define IDC_L2DISTDECMANDATORY          1455
#define IDT_L1DIST                      1455
#define IDC_L2SHOESMANDATORY            1456
#define IDT_L1PACE                      1456
#define IDC_L2SPECSHOESMANDATORY        1457
#define IDT_L2DIST                      1457
#define IDC_L2SPECMINUTESMANDATORY      1458
#define IDT_L3DIST                      1458
#define IDC_L2SPECSECONDSMANDATORY      1459
#define IDT_L3PACE                      1459
#define IDC_L2SPECHOURSMANDATORY        1460
#define IDT_L2PACE                      1460
#define IDC_L2SPECDECMANDATORY          1461
#define IDT_L1TEMP                      1461
#define IDT_L1SPECIALDIST               1462
#define IDT_L1SPECIALPACE               1463
#define IDT_L2TEMP                      1464
#define IDT_L2SPECIALDIST               1465
#define IDT_L2SPECIALPACE               1466
#define IDT_L3TEMP                      1467
#define IDT_L3SPECIALDIST               1468
#define IDT_L3SPECIALPACE               1469
#define IDT_HEIGHT                      1471
#define IDT_WEIGHT                      1472
#define IDT_DIST1                       1473
#define IDT_PACE1                       1474
#define IDT_RUNNING                     1474
#define IDC_L3MINUTESMANDATORY          1475
#define IDT_DIST2                       1475
#define IDT_BIKING                      1475
#define IDC_L3SECONDSMANDATORY          1476
#define IDT_PACE2                       1476
#define IDT_SWIMMING                    1476
#define IDC_L3TEMPMANDATORY             1477
#define IDC_WEIGHTDEC                   1477
#define IDT_STRENGTH                    1477
#define IDC_L3HRMANDATORY               1478
#define IDT_RACING                      1478
#define IDC_L3DISTWHOLEMANDATORY        1479
#define IDT_ADDRUNLOCTEXT               1479
#define IDT_TOTAL                       1479
#define IDC_L3DISTDECMANDATORY          1480
#define IDT_ADDBIKELOCTEXT              1480
#define IDC_PACETYPE1                   1480
#define IDC_L3SHOESMANDATORY            1481
#define IDT_ADDSWIMLOCTEXT              1481
#define IDC_PACETYPE2                   1481
#define IDC_SICK                        1481
#define IDC_L3SPECSHOESMANDATORY        1482
#define IDT_ADDSTRENGTHLOCTEXT          1482
#define IDC_TIMEMINS                    1482
#define IDC_TIME                        1482
#define IDC_L3SPECMINUTESMANDATORY      1483
#define IDT_ADDRUNCOURSETEXT            1483
#define IDC_L3SPECSECONDSMANDATORY      1484
#define IDT_ADDBIKECOURSETEXT           1484
#define IDC_ANIMTIME                    1484
#define IDC_L3SPECHOURSMANDATORY        1485
#define IDT_ADDSWIMCOURSETEXT           1485
#define IDC_ANIMSPIN                    1485
#define IDC_L3SPECDECMANDATORY          1486
#define IDT_ADDDUATHLONCOURSETEXT       1486
#define IDC_PAYPAL                      1486
#define IDT_ADDTRIATHLONCOURSETEXT      1487
#define IDC_PEGRAPH                     1487
#define IDT_ADDRUNSHOESTEXT             1488
#define IDC_ADDLINE                     1488
#define IDT_ADDBIKESHOESTEXT            1489
#define IDC_GRAPH                       1489
#define IDT_ADDBIKETEXT                 1490
#define IDC_COUNTSERIES                 1490
#define IDT_ADDRUNLOCTEXT2              1491
#define IDT_ADDBIKELOCTEXT2             1492
#define IDT_ADDSWIMLOCTEXT2             1493
#define IDT_ADDSTRENGTHLOCTEXT2         1494
#define IDT_ADDRUNCOURSETEXT2           1495
#define IDC_ZAXIS                       1495
#define IDT_ADDBIKECOURSETEXT2          1496
#define IDC_ZAXISTITLE                  1496
#define IDT_ADDSWIMCOURSETEXT2          1497
#define IDC_SERIESTYPE                  1497
#define IDT_ADDDUATHLONCOURSETEXT2      1498
#define IDT_ADDTRIATHLONCOURSETEXT2     1499
#define IDC_POINTTYPE                   1499
#define IDC_CONVERT                     1500
#define IDT_ADDRUNSHOESTEXT2            1500
#define IDC_LINETYPE                    1500
#define IDT_ADDBIKESHOESTEXT2           1501
#define IDC_XGRIDLINES                  1501
#define IDT_ADDBIKETEXT2                1502
#define IDC_YGRIDLINES                  1502
#define IDC_ZGRIDLINES                  1503
#define IDC_GRAPHSUBTITLE               1504
#define IDC_XLOGAXIS                    1505
#define IDC_YLOGAXIS                    1506
#define IDC_ZLOGAXIS                    1507
#define IDC_ROTATE                      1509
#define IDC_PLOTDATATEXT                1510
#define IDC_YAXISZERo                   1510
#define IDC_LINECOLOR                   1511
#define IDC_LABELPOINTS                 1512
#define IDC_POINTCOLOR                  1512
#define IDC_PLOTDATATEXT2               1513
#define IDC_USEFIELD1                   1514
#define IDC_SEARCHTYPETEXT1             1515
#define IDC_UNITSTEXT1                  1516
#define IDC_CUTOFF1                     1517
#define IDC_USEFIELD2                   1518
#define IDC_SEARCHTYPETEXT2             1519
#define IDB_SAVE                        1520
#define IDC_CUTOFF2                     1520
#define IDC_UNITSTEXT2                  1521
#define IDC_USEFIELD3                   1522
#define IDC_SEARCHTYPETEXT3             1523
#define IDC_CUTOFF3                     1524
#define IDC_UNITSTEXT3                  1525
#define IDC_USEFIELD4                   1526
#define IDC_SEARCHTYPETEXT4             1527
#define IDC_CUTOFF4                     1528
#define IDC_UNITSTEXT4                  1529
#define IDC_USEFIELD5                   1530
#define IDC_SEARCHTYPETEXT5             1531
#define IDC_CUTOFF5                     1532
#define IDC_UNITSTEXT5                  1533
#define IDC_USEFIELD6                   1534
#define IDC_SEARCHTYPETEXT6             1535
#define IDC_CUTOFF6                     1536
#define IDC_UNITSTEXT6                  1537
#define IDC_USEFIELD7                   1538
#define IDC_SEARCHTYPETEXT7             1539
#define IDC_FIELD1                      1540
#define IDC_SEARCH                      1541
#define IDC_USEFIELD8                   1542
#define IDC_SEARCHTYPETEXT8             1543
#define IDC_ALLDATES                    1544
#define IDC_SEARCHFOR                   1545
#define IDC_USEFIELD9                   1546
#define IDC_SEARCHTYPETEXT9             1547
#define IDC_CUTOFFFRAC1                 1548
#define IDC_SEARCHPHRASE                1548
#define IDC_CUTOFFFRAC2                 1549
#define IDC_KEEPSAME                    1549
#define IDC_USEFIELD10                  1550
#define IDC_SEARCHTYPETEXT10            1551
#define IDB_EDIT                        1552
#define IDC_CUTOFFFRAC3                 1552
#define IDC_CUTOFFFRAC4                 1553
#define IDC_USEFIELD11                  1554
#define IDC_SEARCHTYPETEXT11            1555
#define IDC_CUTOFFFRAC5                 1556
#define IDC_SEARCHTYPETEXT13            1556
#define IDC_CUTOFFFRAC6                 1557
#define IDC_USEFIELD12                  1558
#define IDC_SEARCHTYPETEXT12            1559
#define IDC_FIELD2                      1562
#define IDC_GRAPHHELP                   1562
#define IDC_FIELD3                      1563
#define IDC_DATEFROM                    1563
#define IDC_FIELD4                      1564
#define IDC_DATETO                      1564
#define IDC_FIELD5                      1565
#define IDC_FIELD6                      1566
#define IDC_FIELD7                      1567
#define IDC_FIELD8                      1568
#define IDC_FIELD9                      1569
#define IDC_FIELD10                     1570
#define IDC_FIELD11                     1571
#define IDC_FIELD12                     1572
#define IDC_LPAREN                      1573
#define IDC_AND                         1574
#define IDC_OR                          1575
#define IDC_NOT                         1576
#define IDC_RPAREN                      1577
#define IDC_CLEAR                       1578
#define IDC_XOR                         1579
#define IDC_HOWTO                       1580
#define IDC_BETWEENDATES                1581
#define IDC_DATESTART                   1582
#define IDC_PRINTRUN                    1583
#define IDC_FILENAME                    1584
#define IDC_PRINTBIKE                   1585
#define IDC_PRINTSWIM                   1586
#define IDC_PRINTSTRENGTH               1587
#define IDC_OPENRESULT                  1588
#define IDC_PRINTTOFILE                 1589
#define IDC_CHANGEFILENAME              1590
#define IDC_RUNDECIMALS                 1591
#define IDC_BIKEDECIMALS                1592
#define IDC_SWIMDECIMALS                1593
#define IDT_RUNDECIMALS                 1594
#define IDT_BIKEDECIMALS                1595
#define IDT_SWIMDECIMALS                1596
#define IDC_PREVNIGHT                   1597
#define IDC_DIST1                       1598
#define IDC_DIST3                       1599
#define IDC_EXPONENT                    1600
#define IDC_FORMULABTN                  1601
#define IDC_PR                          1602
#define IDC_L1LENGTH                    1603
#define IDC_L1PR                        1604
#define IDC_L2LENGTH                    1605
#define IDC_L2PR                        1606
#define IDC_L3LENGTH                    1607
#define IDC_L3PR                        1608
#define IDT_DISTL1                      1609
#define IDC_OVERALLPR                   1610
#define IDC_TRANSITION2PR               1611
#define IDC_TRANSITION1PR               1612
#define IDC_COPYRESULT                  1613
#define IDC_NUMDECIMALS                 1614
#define IDT_DECIMALS                    1615
#define IDC_CLOSEONCOPY                 1616
#define IDC_TIMERACE                    1617
#define IDC_OVERALLTIMERACE             1618
#define IDC_TRANSITION1                 1619
#define IDC_TRANSITIONPR1               1620
#define IDC_TRANSITION2                 1621
#define IDC_TRANSITIONPR2               1622
#define IDC_L1TIMERACE                  1623
#define IDC_L1TIMEOVERALL               1624
#define IDC_L2TIMEOVERALL               1625
#define IDC_L2TIMERACE                  1626
#define IDC_TIMEMANDATORY               1626
#define IDC_L3TIMEOVERALL               1627
#define IDC_DISTMANDATORY               1627
#define IDC_L3TIMERACE                  1628
#define IDC_SPECTIMEMANDATORY           1628
#define IDC_SPECDISTMANDATORY           1629
#define IDC_TRANSMANDATORY              1630
#define IDC_L2TIMEMANDATORY             1631
#define IDC_L2DISTMANDATORY             1632
#define IDC_L2SPECTIMEMANDATORY         1633
#define IDC_L1TIMEMANDATORY             1634
#define IDC_L1DISTMANDATORY             1635
#define IDC_L1SPECTIMEMANDATORY         1636
#define IDC_L3TIMEMANDATORY             1637
#define IDC_L3DISTMANDATORY             1638
#define IDC_L3SPECTIMEMANDATORY         1639
#define IDC_50                          1640
#define IDC_100                         1641
#define IDC_200                         1642
#define IDC_400                         1643
#define IDC_800                         1644
#define IDC_1500                        1645
#define IDC_1600                        1646
#define IDC_1MILE                       1647
#define IDC_3000                        1648
#define IDC_3200                        1649
#define IDC_2MILE                       1650
#define IDC_5000                        1651
#define IDC_10000                       1652
#define IDC_STEEPLE                     1653
#define IDC_INJURYNAME                  1655
#define IDC_DESCRIPTION                 1656
#define IDC_TREATMENT                   1657
#define IDC_HEALED                      1658
#define IDC_NAME                        1659
#define IDC_ADDDATA                     1660
#define ID_VIEW_POOLPRS                 2034
#define ID_VIEW_TRACKPRS                2035
#define ID_FILE_CONVERT                 2036
#define ID_FILE_CONVERT1                2036
#define ID_INDICATOR_PROGRESS           2037
#define ID_VIEW_GRAPHMEDIUM             2038
#define ID_VIEW_GRAPHSMALL              2039
#define ID_VIEW_LOCATIONSUMMARYRUN      2040
#define ID_VIEW_LOCATIONSUMMARYBIKE     2041
#define ID_VIEW_LOCATIONSUMMARYSWIM     2042
#define ID_VIEW_LOCATIONSUMMARYSTRENGTH 2043
#define ID_VIEW_RACESUMMARYRUN          2044
#define ID_VIEW_RACESUMMARYBIKE         2045
#define ID_VIEW_RACESUMMARYSWIM         2046
#define ID_VIEW_RACESUMMARYDUATHLON     2047
#define ID_VIEW_RACESUMMARYTRIATHLON    2048
#define ID_OPTIONS_DELETEWORKOUT        2049
#define ID_OPTIONS_ADDALLDATA           2050
#define ID_OPTIONS_EDITUSERINFO         2051
#define ID_MISC_CALORIES                2052
#define IDR_MAINFRAME2                  2053
#define ID_MISC_SEARCH                  32774
#define IDB_OPENDATAFILE                40001
#define ID_HELP_DONATE                  55555
#define ID_FILE_PRINTTOFILE             55556
#define ID_OPTIONS_ADDUPCOMINGWORKOUT   55557
#define ID_OPTIONS_DELETEUPCOMINGRACE   55558
#define ID_OPTIONS_DELETEUPCOMINGWORKOUT 55559
#define ID_VIEW_INJURYTRACKER           55561

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        319
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1661
#define _APS_NEXT_SYMED_VALUE           223
#endif
#endif
